sys/admin/py/sysmanage/inventory/urls.py
from django.urls import path

from . import views

app_name = "inventory"
urlpatterns = [
    path("", views.main, name="main"),
    path(
        "categorized/<str:category>/<int:category_id>/",
        views.categorized,
        name="categorized",
    ),
    path("server_detail/<int:server_id>/", views.server_detail, name="server_detail"),
]

sys/admin/py/sysmanage/sysmanage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls', namespace='inventory')),
]

sys/admin/py/sysmanage/inventory/models.py
from django.db import models


class OperatingSystem(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class HardwareComponent(models.Model):
    manufacturer = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    model = models.CharField(max_length=50, blank=True, null=True)
    vendor_part_number = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.manufacturer


class Server(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    os = models.ForeignKey(OperatingSystem, on_delete=models.CASCADE)
    services = models.ManyToManyField(Service)
    hardware_component = models.ManyToManyField(HardwareComponent)

    def __str__(self):
        return self.name


class IPAddress(models.Model):
    # address = models.TextField(blank=True, null=True)
    address = models.GenericIPAddressField(blank=True, null=True)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)

    def __str__(self):
        return self.address

sys/admin/py/sysmanage/inventory/views.py
from django.shortcuts import render

from .models import OperatingSystem, Service, HardwareComponent, Server


def main(request):
    os_list = OperatingSystem.objects.all()
    svc_list = Service.objects.all()
    hardware_list = HardwareComponent.objects.all()
    return render(
        request,
        "inventory/main.html",
        {"os_list": os_list, "svc_list": svc_list, "hardware_list": hardware_list},
    )


def categorized(request, category, category_id):
    category_dict = {"os": "Operating System", "svc": "Service", "hw": "Hardware"}

    if category == "os":
        server_list = Server.objects.filter(os__exact=category_id)
        category_name = OperatingSystem.objects.get(id=category_id)

    elif category == "svc":
        server_list = Server.objects.filter(services__exact=category_id)  # 好吗
        category_name = Service.objects.get(id=category_id)  # 详细情况

    elif category == "hw":
        server_list = Server.objects.filter(hardware_component__exact=category_id)
        category_name = HardwareComponent.objects.get(id=category_id)

    else:
        server_list = []
    return render(
        request,
        "inventory/categoried.html",
        {
            "server_list": server_list,
            "category": category_dict[category],  # 分类概览
            "category_name": category_name,  # 详情
        },
    )


def server_detail(request, server_id):
    server = Server.objects.get(id=server_id)
    return render(request, "inventory/server_detail.html", {"server": server})

sys/admin/py/sysmanage/inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}资产管理清单{% endblock %}</title>
</head>
<body>
	<div><a href="/">资产管理清单</a></div>
	{% block content %}未添加内容{% endblock %}
</body>
</html>

sys/admin/py/sysmanage/inventory/templates/inventory/categoried.html
{% extends "base.html" %}

{% block title %}Server List{% endblock %}

{% block content %}
<h1>{{ category }}::{{ category_name }}</h1>
<div>
  <ul>
    {% for s in server_list %}
    <li><a href="{% url 'inventory:server_detail' s.id %}">{{ s.name }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

sys/admin/py/sysmanage/inventory/templates/inventory/main.html
{% extends "base.html" %}

{% block title %}Server Inventory Category View{% endblock %}

{% block content %}
<div>
  <h2>Operating Systems</h2> {# 操作系统分类 #}
  <ul>
    {% for o in os_list %}
    <li><a href="{% url 'inventory:categorized' 'os' o.id %}">{{ o.name }}</a></li>
    {% endfor %}
  </ul>
</div>

<div>
  <h2>Services</h2> {# 服务分类#}
  <ul>
    {% for s in svc_list %}
    <li><a href="{% url 'inventory:categorized' 'svc' s.id %}">{{ s.name }}</a></li>
    {% endfor %}
  </ul>
</div>

<div>
  <h2>Hardware Components</h2> {# 硬件分类 #}
  <ul>
    {% for h in hardware_list %}
    <li><a href="{% url 'inventory:categorized' 'hw' h.id %}">{{ h.manufacturer }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

sys/admin/py/sysmanage/inventory/templates/inventory/server_detail.html
{% extends "base.html" %}

{% block title %}Server Detail{% endblock %}

{% block content %}
<div>
  Name: {{ server.name }}
</div>

<div>
  Description: {{ server.description }}
</div>

<div>
  OS: {{ server.os.name }}
</div>

<div>
  <div>Services:</div>
  <ul>
    {% for service in server.services.all %}
    <li>{{ service.name }}</li>
    {% endfor %}
  </ul>
</div>

<div>
  <div>Hardware:</div>
  <ul>
    {% for hw in server.hardware_component.all %}
    <li>{{ hw.manufacturer }} {{ hw.type }} {{ hw.model }}</li>
    {% endfor %}
  </ul>
</div>

<div>
  <div>IP Addresses:</div>
  <ul>
    {% for ip in server.ipaddress_set.all %}
    <li>{{ ip.address }}</li>
    {% endfor %}
  </ul>
</div>

{% endblock %}